### ISSUE TITLE
DEP0100 for DirectXTKSimpleSample (Universal WIndows) local machine

### ISSUE THREAD

**Issue by ChrisKing340** [walbourn/directxtk-samples#2]
Hi Mark,
The solution on compile for SimpleSampleWindows10DX12 gives DEP0100.  Using Microsoft Visual Studio Community 2019 Version 16.6.5.  Is this code accessible to me without a developer license?  Thank you.

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0100: Please ensure that target device has developer mode enabled. Could not obtain a developer license due to error 800704C7.	DirectXTKSimpleSample

**Comment by walbourn** [comment]
To do UWP development, you need to enable *Developer Mode* on your Windows 10 system. See [Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development).

This is not specific to my samples.
